In [2]:
import torch
import tqdm

In [8]:
a=torch.randn(2,3)
b=torch.randn(3,2)


In [9]:
a,b

(tensor([[-0.2889,  0.1592, -0.5447],
         [ 0.1813,  0.1824, -0.3810]]), tensor([[ 1.5898, -0.6201],
         [-0.1831, -0.4346],
         [ 1.3867,  0.1676]]))

In [10]:
print(torch.mm(a,b))
print(torch.matmul(a,b))

tensor([[-1.2438,  0.0187],
        [-0.2735, -0.2555]])
tensor([[-1.2438,  0.0187],
        [-0.2735, -0.2555]])


In [13]:
t = torch.randn(2,3,4,5)
t.transpose(3,0).shape

torch.Size([5, 3, 4, 2])

In [14]:
a=torch.tensor([1,0,2,3])
a

tensor([1, 0, 2, 3])

In [31]:
a=torch.Tensor([[[1,2,3],[4,5,6]]])
b=torch.Tensor([1,2,3,4,5,6])
c = a.view(-1,3,2)
print(c,c.shape)
print(b.view(1,6))

tensor([[[1., 2.],
         [3., 4.],
         [5., 6.]]]) torch.Size([1, 3, 2])
tensor([[1., 2., 3., 4., 5., 6.]])


In [35]:
g = lambda x:x+3
g(1)

4

In [53]:
import torch.nn.functional as F

x1= torch.Tensor( [[1,2,3,4],[1,3,4,5],[3,4,5,6]])
x1, x1.shape

(tensor([[1., 2., 3., 4.],
         [1., 3., 4., 5.],
         [3., 4., 5., 6.]]), torch.Size([3, 4]))

In [59]:
y12 = F.softmax(x1,dim = -1)
y12

tensor([[0.0321, 0.0871, 0.2369, 0.6439],
        [0.0120, 0.0889, 0.2418, 0.6572],
        [0.0321, 0.0871, 0.2369, 0.6439]])

In [60]:
y120 = F.softmax(x1,dim = 1)
y120

tensor([[0.0321, 0.0871, 0.2369, 0.6439],
        [0.0120, 0.0889, 0.2418, 0.6572],
        [0.0321, 0.0871, 0.2369, 0.6439]])

In [64]:
import torch.nn as nn
softmax = nn.LogSoftmax(dim=-1)
print([max(x) for x in softmax(x1)])

[tensor(-0.4402), tensor(-0.4197), tensor(-0.4402)]


In [63]:
softmax(x1)

tensor([[-3.4402, -2.4402, -1.4402, -0.4402],
        [-4.4197, -2.4197, -1.4197, -0.4197],
        [-3.4402, -2.4402, -1.4402, -0.4402]])

In [17]:
from tqdm import trange
import pandas as pd
import numpy as np
from tqdm import trange
import time


In [39]:

for i in trange(100000000):
    #do something
    pass



  0%|          | 0/100000000 [00:00<?, ?it/s]

  0%|          | 356460/100000000 [00:00<00:27, 3564569.41it/s]

  1%|          | 739284/100000000 [00:00<00:27, 3639774.96it/s]

  1%|          | 1141697/100000000 [00:00<00:26, 3747138.31it/s]

  2%|▏         | 1589454/100000000 [00:00<00:24, 3939955.90it/s]

  2%|▏         | 2078427/100000000 [00:00<00:23, 4183707.04it/s]

  3%|▎         | 2583180/100000000 [00:00<00:22, 4410127.26it/s]

  3%|▎         | 3098164/100000000 [00:00<00:21, 4608713.00it/s]

  4%|▎         | 3627080/100000000 [00:00<00:20, 4793724.05it/s]

  4%|▍         | 4170235/100000000 [00:00<00:19, 4968756.83it/s]

  5%|▍         | 4724305/100000000 [00:01<00:18, 5127543.28it/s]

  5%|▌         | 5299308/100000000 [00:01<00:17, 5299646.46it/s]

  6%|▌         | 5895125/100000000 [00:01<00:17, 5481381.94it/s]

  6%|▋         | 6464355/100000000 [00:01<00:16, 5542995.41it/s]

  7%|▋         | 7020881/100000000 [00:01<00:16, 5549641.81it/s]

  8%|▊         | 7590924/1000

 66%|██████▌   | 65626970/100000000 [00:11<00:06, 5622380.67it/s]

 66%|██████▌   | 66202413/100000000 [00:11<00:05, 5661340.37it/s]

 67%|██████▋   | 66794170/100000000 [00:11<00:05, 5735846.33it/s]

 67%|██████▋   | 67369765/100000000 [00:11<00:05, 5717753.59it/s]

 68%|██████▊   | 67954618/100000000 [00:11<00:05, 5756098.40it/s]

 69%|██████▊   | 68536967/100000000 [00:11<00:05, 5776136.78it/s]

 69%|██████▉   | 69131100/100000000 [00:11<00:05, 5824719.64it/s]

 70%|██████▉   | 69727472/100000000 [00:12<00:05, 5865719.75it/s]

 70%|███████   | 70315752/100000000 [00:12<00:05, 5870830.89it/s]

 71%|███████   | 70903191/100000000 [00:12<00:04, 5848659.00it/s]

 71%|███████▏  | 71488980/100000000 [00:12<00:04, 5851422.73it/s]

 72%|███████▏  | 72087034/100000000 [00:12<00:04, 5889557.92it/s]

 73%|███████▎  | 72679328/100000000 [00:12<00:04, 5899530.44it/s]

 73%|███████▎  | 73290838/100000000 [00:12<00:04, 5962573.44it/s]

 74%|███████▍  | 73887353/100000000 [00:12<00:04, 5920409.24it

KeyboardInterrupt: 

In [37]:
sentences = []
sentence = []
lines = 0
with open("c_500.csv", "r", encoding="utf-8") as f:
    for line in f.readlines():
        sentences.append(line)
        lines += 1
with trange(100) as t:
    try:
        for i in t:
            t.set_description("Processing {args}".format(args="test"))
            sentence.append(sentences[i].split(',')[2])
    except KeyboardInterrupt:
        t.close()
        raise
    t.close()
# for i in trange(lines):
#     sentence.append(sentences[i].split(',')[2])
#     time.sleep(0.0001)
        



  0%|          | 0/100 [00:00<?, ?it/s]

Processing test:   0%|          | 0/100 [00:00<?, ?it/s]

Processing test:   0%|          | 0/100 [00:00<?, ?it/s]

Processing test:   0%|          | 0/100 [00:00<?, ?it/s]

Processing test:   0%|          | 0/100 [00:00<?, ?it/s]

Processing test:   0%|          | 0/100 [00:00<?, ?it/s]

Processing test:   0%|          | 0/100 [00:00<?, ?it/s]

Processing test:   0%|          | 0/100 [00:00<?, ?it/s]

Processing test:   0%|          | 0/100 [00:00<?, ?it/s]

Processing test:   0%|          | 0/100 [00:00<?, ?it/s]

Processing test:   0%|          | 0/100 [00:00<?, ?it/s]

Processing test:   0%|          | 0/100 [00:00<?, ?it/s]

Processing test:   0%|          | 0/100 [00:00<?, ?it/s]

Processing test:   0%|          | 0/100 [00:00<?, ?it/s]

Processing test:   0%|          | 0/100 [00:00<?, ?it/s]

Processing test:   0%|          | 0/100 [00:00<?, ?it/s]

Processing test:   0%|          | 0/100 [00:00<?, ?it/s]

Processing test:   0%|       